Mail: Accessing style sheets can be rejected in "unset HTML colors"
The WebKitGTK can reject accessing some style sheets with error:

    SecurityError: Not allowed to access cross-origin stylesheet

which is received as an exception, thus it stops the "unset HTML
colors" code too early, before it finishes.

Related to https://gitlab.gnome.org/GNOME/evolution/-/issues/3254