Revert "Updated German help translation"
This reverts commit 83ce49534bc02a574b77a4072fdb973f43db8acf.

This commit introduced a build break:

    Error: Could not merge translations:
    'NoneType' object has no attribute 'node'
    make: *** [de/de.stamp] Error 1