Mail: Correct function prototype declaration (-Wenum-int-mismatch)
src/mail/em-composer-utils.c:4738:1: warning: conflicting types for
‘em_utils_reply_to_message’ due to enum/integer mismatch; have ‘void(EMsgComposer *,
CamelMimeMessage *, CamelFolder *, const gchar *, EMailReplyType,  EMailReplyStyle,
 EMailPartList *, CamelInternetAddress *, EMailReplyFlags)’ {aka ‘void(struct
_EMsgComposer *, struct _CamelMimeMessage *, struct _CamelFolder *, const char *,
EMailReplyType,  EMailReplyStyle,  struct _EMailPartList *, struct _CamelInternetAddress *,
EMailReplyFlags)’} [-Wenum-int-mismatch]
 4738 | em_utils_reply_to_message (EMsgComposer *composer,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/mail/em-composer-utils.c:50:
src/mail/em-composer-utils.h:78:17: note: previous declaration of ‘em_utils_reply_to_message’
with type ‘void(EMsgComposer *, CamelMimeMessage *, CamelFolder *, const gchar *,
EMailReplyType,  EMailReplyStyle,  EMailPartList *, CamelInternetAddress *, guint32)’
{aka ‘void(struct _EMsgComposer *, struct _CamelMimeMessage *, struct _CamelFolder *,
const char *, EMailReplyType,  EMailReplyStyle,  struct _EMailPartList *,
struct _CamelInternetAddress *, unsigned int)’}
   78 | void            em_utils_reply_to_message       (EMsgComposer *composer,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~